In [1]:
import numpy as np
from numpy import array,zeros 

A=array([[-2,1,2,0,0,0],
        [-1,-1,0,0,0,0],
        [0,0,-2,1,2,0],
        [0,1,-1,-1,0,0],
        [0,0,0,0,-2,-3],
        [0,0,0,1,-1,-1]],float)
b=array([0,1,0,0,0,0],float)
n=len(b)
x=zeros(n,float)


for k in range(n-1):
    for i in range(k+1, n):
        if A[i,k] == 0 : continue
        factor = A[k,k] / A[i,k]
        for j in range(k,n):
            A[i,j] = A[k,j] - A[i,j]*factor
        b[i] = b[k] - b[i]*factor
        print(f"After elimination # {k+1}:")
        print('A:\n',A)
        print('b:',b)
        print("")
        

x[n-1] = b[n-1] / A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum_ax = 0
    for j in range(i+1,n):
        sum_ax += A[i,j] * x[j]
    x[i] = (b[i] - sum_ax) / A[i,i]

print('Solution using the Gauss elimination:\n x =',x)
print("")


print('Solution using numpy: \n x = %s' % np.linalg.solve(A,b))

After elimination # 1:
A:
 [[-2.  1.  2.  0.  0.  0.]
 [ 0.  3.  2.  0.  0.  0.]
 [ 0.  0. -2.  1.  2.  0.]
 [ 0.  1. -1. -1.  0.  0.]
 [ 0.  0.  0.  0. -2. -3.]
 [ 0.  0.  0.  1. -1. -1.]]
b: [ 0. -2.  0.  0.  0.  0.]

After elimination # 2:
A:
 [[-2.  1.  2.  0.  0.  0.]
 [ 0.  3.  2.  0.  0.  0.]
 [ 0.  0. -2.  1.  2.  0.]
 [ 0.  0.  5.  3.  0.  0.]
 [ 0.  0.  0.  0. -2. -3.]
 [ 0.  0.  0.  1. -1. -1.]]
b: [ 0. -2.  0. -2.  0.  0.]

After elimination # 3:
A:
 [[-2.   1.   2.   0.   0.   0. ]
 [ 0.   3.   2.   0.   0.   0. ]
 [ 0.   0.  -2.   1.   2.   0. ]
 [ 0.   0.   0.   2.2  2.   0. ]
 [ 0.   0.   0.   0.  -2.  -3. ]
 [ 0.   0.   0.   1.  -1.  -1. ]]
b: [ 0.  -2.   0.  -0.8  0.   0. ]

After elimination # 4:
A:
 [[-2.   1.   2.   0.   0.   0. ]
 [ 0.   3.   2.   0.   0.   0. ]
 [ 0.   0.  -2.   1.   2.   0. ]
 [ 0.   0.   0.   2.2  2.   0. ]
 [ 0.   0.   0.   0.  -2.  -3. ]
 [ 0.   0.   0.   0.   4.2  2.2]]
b: [ 0.  -2.   0.  -0.8  0.  -0.8]

After elimination # 5:
A:
 [[-2.    